spark-solutions/spree

frontend/app/controllers/spree/checkout_controller.rb

https://spark-solutions.atlassian.net/browse/SD-511
CheckoutControllerDecorator: https://github.com/spark-solutions/spree-designs/blob/5a943ad7ad16cce8b50cdaafb7bb1e60ec275c22/app/controllers/spree/checkout_controller_decorator.rb

[SD-511] Move CheckoutControllerDecorator from spree-designs

---

frontend/app/helpers/spree/addresses_helper.rb

https://spark-solutions.atlassian.net/browse/SD-519
AddressesHelper in `spree-designs`: https://github.com/spark-solutions/spree-designs/blob/2de8c88961df52c50356a5ee2a93faed0e8ff778/app/helpers/spree/addresses_helper.rb

[SD-519] Move AddressesHelper from spree-design

---

frontend/app/assets/stylesheets/spree/frontend/application.scss

https://spark-solutions.atlassian.net/browse/SD-517

[SD-517] Fix import of bootstrap styles

---

frontend/app/views/spree/checkout/_delivery.html.erb

https://spark-solutions.atlassian.net/browse/SD-528

[SD-528] Move "checkout delivery" view

---

frontend/app/views/spree/checkout/_payment.html.erb
frontend/app/views/spree/checkout/payment/_gateway.html.erb

https://spark-solutions.atlassian.net/browse/SD-531

[SD-531] Move "checkout payment" view

---

frontend/app/views/spree/checkout/_confirm.html.erb

https://spark-solutions.atlassian.net/browse/SD-532

[SD-532] Move "checkout confirm" view

---

frontend/app/assets/stylesheets/spree/frontend/views/spree/orders/show.scss

Connected with https://github.com/spark-solutions/spree-designs/pull/233

[SD-400] Order placed page fixes

---

frontend/app/assets/javascripts/spree/frontend/views/spree/products/modal_carousel.js

The js didn't work well when there was only one image because js depended on existence of thumbnails.

SD-421 Fix/single image broken pdp javascript

---

frontend/app/helpers/spree/navigation_helper.rb
frontend/app/views/spree/shared/_category_nav_bar.html.erb
frontend/app/views/spree/shared/_main_nav_bar.html.erb
frontend/app/views/spree/shared/_mobile_navigation.html.erb

https://spark-solutions.atlassian.net/browse/SD-542

[SD-542] Move NavigationHelper

---

core/app/helpers/spree/products_helper.rb
frontend/app/helpers/spree/structured_data_helper.rb

https://spark-solutions.atlassian.net/browse/SD-558

[SD-558] Move helpers from spree-designs

---

frontend/app/controllers/spree/products_controller.rb

I add this here because ProductsController should be removed on spree-design repo when SD-560 was done and the controller was moved to this repo.

SD-468/560 Adjust to ProductsController changes

---

core/app/models/spree/image.rb
core/app/models/spree/image/configuration/active_storage.rb

https://spark-solutions.atlassian.net/browse/SD-562
Related code in `spree-designs`: https://github.com/spark-solutions/spree-designs/blob/fc48c06952d93af6b7834098329e15bbb23c84a5/app/models/spree/image_decorator.rb

[SD-562] Move new code for Spree::Image model

---

frontend/app/assets/stylesheets/spree/frontend/views/spree/shared/carousel/single.scss

Connected with https://github.com/spark-solutions/spree-designs/pull/210

[SD-502] Adds arrows for portrait tablet on PDP

---

frontend/app/controllers/spree/addresses_controller.rb
frontend/app/views/spree/address/_form.html.erb
frontend/app/views/spree/addresses/_form.html.erb
frontend/app/views/spree/addresses/edit.html.erb
frontend/app/views/spree/addresses/new.html.erb
frontend/app/views/spree/orders/show.html.erb
frontend/app/views/spree/users/edit.html.erb
frontend/app/views/spree/users/show.html.erb

for comparison: https://github.com/spark-solutions/spree-designs/pull/245

SD-564 Migrate Account

---

frontend/app/helpers/spree/structured_data_helper.rb

https://github.com/spree/spree/pull/9635#discussion_r349103959

Fix structured_images

---

frontend/app/controllers/spree/addresses_controller.rb

https://github.com/spree/spree/pull/9635#discussion_r349102801

Fix account_path

---

frontend/app/assets/stylesheets/spree/frontend/components-bootstrap/carousel.scss
frontend/app/assets/stylesheets/spree/frontend/variables/variables.scss
frontend/app/assets/stylesheets/spree/frontend/views/spree/products/show.scss
frontend/app/assets/stylesheets/spree/frontend/views/spree/shared/carousel/single.scss
frontend/app/assets/stylesheets/spree/frontend/views/spree/shared/carousel/thumbnails.scss
frontend/app/views/spree/products/show.html.erb
frontend/app/views/spree/shared/carousel/_thumbnails.html.erb

https://github.com/spark-solutions/spree-designs/pull/253/files

SD-421 Fullscreen zoom on PDP

---

frontend/app/assets/javascripts/spree/frontend/views/spree/products/cart_form.js
frontend/spec/features/cart_spec.rb

https://spark-solutions.atlassian.net/browse/SD-588

Allow to add to cart a Product with Variants and without Option Values

---

frontend/app/assets/stylesheets/spree/frontend/application.scss
frontend/app/assets/stylesheets/spree/frontend/views/spree/checkout/payment.scss
frontend/app/views/spree/checkout/_payment.html.erb
frontend/spec/features/order_spec.rb

Support other kind of payments in checkout

---

frontend/app/assets/stylesheets/spree/frontend/components-bootstrap/carousel.scss
frontend/app/views/spree/home/_carousel.html.erb

Connected with https://github.com/spark-solutions/spree-designs/pull/199

[SD-260][SD-261] Fixes home page arrows position

---

frontend/app/views/spree/shared/_login.html.erb

Moved from https://github.com/spark-solutions/spree_auth_devise/commit/b08d1c672fec73bec46facfff47d36161452a691#diff-57f176370ecf4ce791409951a8ca1804
Delete https://github.com/spark-solutions/spree_auth_devise/pull/8

move shared/_login

---

api/app/controllers/spree/graphql/graphql_controller.rb
api/app/graphql/spree/graphql_schema.rb
api/app/graphql/spree/jwt_token.rb
api/app/graphql/spree/mutations/base_mutation.rb
api/app/graphql/spree/mutations/cart.rb
api/app/graphql/spree/resolvers/base.rb
api/app/graphql/spree/resolvers/order.rb
api/app/graphql/spree/resolvers/product.rb
api/app/graphql/spree/types/money.rb
api/app/graphql/spree/types/mutation_type.rb
api/app/graphql/spree/types/order_type.rb
api/app/graphql/spree/types/product_type.rb
api/app/graphql/spree/types/query_type.rb
api/app/models/spree/api_configuration.rb
api/app/models/spree/graphql_dependencies.rb
api/config/routes.rb
api/lib/spree/api/engine.rb
api/lib/spree_api.rb
api/spec/controllers/spree/graphql/graphql_order_spec.rb
api/spec/controllers/spree/graphql/graphql_product_spec.rb
api/spec/controllers/spree/graphql_controller_spec.rb
api/spree_api.gemspec

WIP authentication
WIP on auth
using JWT token for auth
WIP graphql auth
wip graphql jwt specs
wip
WIP
wip on graphql
working on GraphQL auth
naming fixes
Work on GraphQL add pagination
fix issue with wrong graphql parameter name in spec
add money type coercion and fields to order entity
refactor specs add products resource
separate graphql specs by resource + add product
add create cart api
working on graphql

GraphQL implementation
